### ISSUE TITLE
目录里面的01、02、03和Readme文件是什么关系？

### ISSUE THREAD

**Issue by anxiaoyi** [helloqingfeng/Awsome-Front-End-learning-resource#11]
各个章节和readme是什么关系？readme也有资源，01章节、02章节也有资源

**Comment by helloqingfeng** [comment]
目录里面的01、02主要是为了区分各个资源而进行的一个排序，每个目录下的资源在readme里面都有链接，但和目录序号不是从上到下一一对应的关系
