### ISSUE TITLE
❓ It looks interesting. What about translating it in english...

### ISSUE THREAD

**Issue by pitpit** [helloqingfeng/Awsome-Front-End-learning-resource#6]
... so that non-chinese speaking developers can understand it

**Comment by helloqingfeng** [comment]
I'm not good at English. can you help translate it in English?

**Comment by scofieldfan** [comment]
I can also help to translate it to English. But i think we need a native English speaking developer to help verify it.

**Comment by pitpit** [comment]
unfortunately @helloqingfeng I can't read chinese, so I can't help you to translate it into english... :(

**Comment by thulasipavankumar** [comment]
cant we have a translate button  in the page which can translate the page using google api

> (just a thought)
