### ISSUE TITLE
建议用git submodule方式收录github资源库

### ISSUE THREAD

**Issue by huguangju** [helloqingfeng/Awsome-Front-End-learning-resource#7]
可参照这个repo [maven-framework-project](https://github.com/v5developer/maven-framework-project) :

`以git submodule的方式添加进来，一来是尊重原作者的劳动成果，二来实时与原作者库同步，保持最新。`

参考：[7.11 Git 工具 - 子模块](https://git-scm.com/book/zh/v2/Git-%E5%B7%A5%E5%85%B7-%E5%AD%90%E6%A8%A1%E5%9D%97)

**Comment by helloqingfeng** [comment]
很不错的建议，现在还在学习探索中，git使用还不太熟练，后面我技术成熟些了，会按照这个方案改进的，谢谢哈
